spring.application.name: springboot-jwt-authservice

server.port: 8057

spring.datasource.url: jdbc:mysql://localhost:3306/userauthdb
spring.datasource.username: root
spring.datasource.password: root
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true  